package main

import (
        "fmt"
        "strings"
)

// tempStructs is set by generateGRPCFiles before calling the adapter
// generators. It maps struct type names to their field info, so the
// adapter generators can emit field-by-field conversion code.
var tempStructs map[string]*grpcStruct

// findStruct looks up a struct by name from tempStructs.
func findStruct(name string) (*grpcStruct, bool) {
        if tempStructs == nil {
                return nil, false
        }
        s, ok := tempStructs[name]
        return s, ok
}

// generate_grpc_adapters.go — Phase 5 (server adapter) + Phase 6 (client wrapper).
//
// The server adapter imports the user's handlers package and converts between
// the generated protobuf message types (used for gRPC wire serialization) and
// the user's Go struct types (used by the business logic).
//
// The user's handlers package path is: <modulePath>/handlers

// ─── Phase 5: Server Adapter ─────────────────────────────────────────────────

func generateServerAdapter(modulePath string, iface *grpcInterface) (string, error) {
        var b strings.Builder

        b.WriteString("// Code generated by breeze generate grpc. DO NOT EDIT.\n\n")
        b.WriteString(fmt.Sprintf("package %s\n\n", iface.Name))

        handlersImport := modulePath + "/handlers"
        b.WriteString(fmt.Sprintf(`import (
        "context"

        "google.golang.org/grpc/codes"
        "google.golang.org/grpc/status"

        handlers %q
)

`, handlersImport))

        // Adapter struct — holds the user's implementation.
        b.WriteString(fmt.Sprintf("// %sGRPCServer adapts a user-provided handlers.%s implementation\n", iface.Name, iface.Name))
        b.WriteString(fmt.Sprintf("// to the generated gRPC %sServer interface.\n", iface.Name))
        b.WriteString(fmt.Sprintf("type %sGRPCServer struct {\n", iface.Name))
        b.WriteString(fmt.Sprintf("\timpl handlers.%s\n", iface.Name))
        b.WriteString("}\n\n")

        // Constructor.
        b.WriteString(fmt.Sprintf("// New%sGRPCServer wraps the given handlers.%s implementation.\n", iface.Name, iface.Name))
        b.WriteString(fmt.Sprintf("func New%sGRPCServer(impl handlers.%s) *%sGRPCServer {\n", iface.Name, iface.Name, iface.Name))
        b.WriteString(fmt.Sprintf("\treturn &%sGRPCServer{impl: impl}\n", iface.Name))
        b.WriteString("}\n\n")

        // Method forwarders.
        for _, m := range iface.Methods {
                emitServerMethodForwarder(&b, iface.Name, m)
        }

        return b.String(), nil
}

func emitServerMethodForwarder(b *strings.Builder, serviceName string, m grpcMethod) {
        rpcName := m.Name
        recvType := fmt.Sprintf("%sGRPCServer", serviceName)

        switch m.Kind {
        case grpcUnary:
                // gRPC server method: Method(ctx, *PbReq) (*PbResp, error)
                // User method:        Method_GRPC(ctx, handlers.Req) (*handlers.Resp, error)
                b.WriteString(fmt.Sprintf("func (s *%s) %s(ctx context.Context, req *%s) (*%s, error) {\n",
                        recvType, rpcName, m.ReqType, m.RespType))
                // Convert pb request → handlers request (field-by-field copy).
                b.WriteString(fmt.Sprintf("\tuserReq := handlers.%s{\n", m.ReqType))
                if s, ok := findStruct(m.ReqType); ok {
                        for _, f := range s.Fields {
                                b.WriteString(fmt.Sprintf("\t\t%s: req.Get%s(),\n", f.GoName, f.GoName))
                        }
                }
                b.WriteString("\t}\n")
                // Call user implementation.
                b.WriteString(fmt.Sprintf("\tresp, err := s.impl.%s(ctx, userReq)\n", m.Name))
                b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
                // Convert handlers response → pb response.
                b.WriteString(fmt.Sprintf("\treturn &%s{\n", m.RespType))
                if s, ok := findStruct(m.RespType); ok {
                        for _, f := range s.Fields {
                                b.WriteString(fmt.Sprintf("\t\t%s: resp.%s,\n", f.GoName, f.GoName))
                        }
                }
                b.WriteString("\t}, nil\n")
                b.WriteString("}\n\n")

        case grpcServerStream:
                b.WriteString(fmt.Sprintf("func (s *%s) %s(req *%s, stream %s) error {\n",
                        recvType, rpcName, m.ReqType, m.StreamType))
                b.WriteString("\t// ServerSideStreaming adapter — streaming not yet fully supported.\n")
                b.WriteString("\t// The unary path works; streaming requires stream interface generation.\n")
                b.WriteString(fmt.Sprintf("\treturn status.Errorf(codes.Unimplemented, \"%s streaming not yet supported\")\n", rpcName))
                b.WriteString("}\n\n")

        case grpcClientStream:
                b.WriteString(fmt.Sprintf("func (s *%s) %s(stream %s) (*%s, error) {\n",
                        recvType, rpcName, m.StreamType, m.RespType))
                b.WriteString("\t// ClientSideStreaming adapter — streaming not yet fully supported.\n")
                b.WriteString(fmt.Sprintf("\treturn nil, status.Errorf(codes.Unimplemented, \"%s streaming not yet supported\")\n", rpcName))
                b.WriteString("}\n\n")

        case grpcBidiStream:
                b.WriteString(fmt.Sprintf("func (s *%s) %s(stream %s) error {\n",
                        recvType, rpcName, m.StreamType))
                b.WriteString("\t// Bidirectional adapter — streaming not yet fully supported.\n")
                b.WriteString(fmt.Sprintf("\treturn status.Errorf(codes.Unimplemented, \"%s streaming not yet supported\")\n", rpcName))
                b.WriteString("}\n\n")
        }
}

// ─── Phase 6: Client Wrapper ─────────────────────────────────────────────────

func generateClientWrapper(modulePath string, iface *grpcInterface) (string, error) {
        var b strings.Builder

        b.WriteString("// Code generated by breeze generate grpc. DO NOT EDIT.\n\n")
        b.WriteString(fmt.Sprintf("package %s\n\n", iface.Name))

        handlersImport := modulePath + "/handlers"
        b.WriteString(fmt.Sprintf(`import (
        "context"

        "google.golang.org/grpc"

        handlers %q
)

`, handlersImport))

        // Client struct.
        b.WriteString(fmt.Sprintf("// %sGRPCClient wraps the generated gRPC client and exposes typed\n", iface.Name))
        b.WriteString("// methods matching the original _GRPC signatures (minus the _GRPC suffix).\n")
        b.WriteString(fmt.Sprintf("type %sGRPCClient struct {\n", iface.Name))
        b.WriteString(fmt.Sprintf("\tclient %sClient\n", iface.Name))
        b.WriteString("}\n\n")

        // Constructor.
        b.WriteString(fmt.Sprintf("// New%sGRPCClient creates a typed client using the given gRPC connection.\n", iface.Name))
        b.WriteString(fmt.Sprintf("func New%sGRPCClient(cc grpc.ClientConnInterface) *%sGRPCClient {\n", iface.Name, iface.Name))
        b.WriteString(fmt.Sprintf("\treturn &%sGRPCClient{client: New%sClient(cc)}\n", iface.Name, iface.Name))
        b.WriteString("}\n\n")

        // Typed client methods.
        for _, m := range iface.Methods {
                emitClientMethodWrapper(&b, iface.Name, m)
        }

        return b.String(), nil
}

func emitClientMethodWrapper(b *strings.Builder, serviceName string, m grpcMethod) {
        rpcName := m.Name
        recvType := fmt.Sprintf("%sGRPCClient", serviceName)

        switch m.Kind {
        case grpcUnary:
                // Typed client method: Method(ctx, handlers.Req) (*handlers.Resp, error)
                b.WriteString(fmt.Sprintf("func (c *%s) %s(ctx context.Context, req handlers.%s) (*handlers.%s, error) {\n",
                        recvType, rpcName, m.ReqType, m.RespType))
                // Convert handlers request → pb request.
                b.WriteString(fmt.Sprintf("\tpbReq := &%s{\n", m.ReqType))
                if s, ok := findStruct(m.ReqType); ok {
                        for _, f := range s.Fields {
                                b.WriteString(fmt.Sprintf("\t\t%s: req.%s,\n", f.GoName, f.GoName))
                        }
                }
                b.WriteString("\t}\n")
                // Call the gRPC client.
                b.WriteString(fmt.Sprintf("\tpbResp, err := c.client.%s(ctx, pbReq)\n", rpcName))
                b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
                // Convert pb response → handlers response.
                b.WriteString(fmt.Sprintf("\treturn &handlers.%s{\n", m.RespType))
                if s, ok := findStruct(m.RespType); ok {
                        for _, f := range s.Fields {
                                b.WriteString(fmt.Sprintf("\t\t%s: pbResp.Get%s(),\n", f.GoName, f.GoName))
                        }
                }
                b.WriteString("\t}, nil\n")
                b.WriteString("}\n\n")

        case grpcServerStream:
                b.WriteString(fmt.Sprintf("func (c *%s) %s(ctx context.Context, req handlers.%s) (%s, error) {\n",
                        recvType, rpcName, m.ReqType, m.StreamType))
                b.WriteString(fmt.Sprintf("\tpbReq := &%s{\n", m.ReqType))
                if s, ok := findStruct(m.ReqType); ok {
                        for _, f := range s.Fields {
                                b.WriteString(fmt.Sprintf("\t\t%s: req.%s,\n", f.GoName, f.GoName))
                        }
                }
                b.WriteString("\t}\n")
                b.WriteString(fmt.Sprintf("\treturn c.client.%s(ctx, pbReq)\n", rpcName))
                b.WriteString("}\n\n")

        case grpcClientStream, grpcBidiStream:
                b.WriteString(fmt.Sprintf("func (c *%s) %s(ctx context.Context) (%s, error) {\n",
                        recvType, rpcName, m.StreamType))
                b.WriteString(fmt.Sprintf("\treturn c.client.%s(ctx)\n", rpcName))
                b.WriteString("}\n\n")
        }
}
