package main

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"
)

const registryFileName = "routes_generated.go"

const registryHeader = `// Code generated by ` + "`breeze generate`" + `. DO NOT EDIT outside the
// marker blocks below — re-running generate for a resource replaces its
// block, and hand edits outside markers will be lost.

package main
`

// registryTemplate is the routes_generated.go content written by `breeze
// new`, before anything has been generated. It deliberately omits the
// handlers import — Go rejects unused imports, and there's nothing to
// reference until the first `generate` call adds a block.
func registryTemplate(modulePath string) string {
	return registryHeader + `
import (
	"github.com/nelthaarion/breeze"
)

func RegisterGeneratedRoutes(router *breeze.Router) {
}
`
}

func blockMarkers(name string) (start, end string) {
	return fmt.Sprintf("// breeze:route:%s:start", name), fmt.Sprintf("// breeze:route:%s:end", name)
}

// ensureImports adds each import line to the import block if it isn't
// already present — e.g. the project's handlers package, or (for resource
// generation) the swagger and middleware packages. It's a no-op for any
// import a prior generate call already added.
func ensureImports(content string, importLines []string) string {
	breezeImport := `"github.com/nelthaarion/breeze"`
	for _, line := range importLines {
		if strings.Contains(content, line) {
			continue
		}
		content = strings.Replace(content, breezeImport, breezeImport+"\n\n\t"+line, 1)
	}
	return content
}

// upsertRouteBlock inserts or replaces the marker block for name inside the
// RegisterGeneratedRoutes function body of routes_generated.go, creating the
// file from the template if it doesn't exist yet. body is the raw Go source
// for the block's contents (without the marker comments). extraImports are
// additional import lines (e.g. swagger/middleware packages) the block needs
// beyond the handlers package, which is always ensured.
func upsertRouteBlock(modulePath, name, body string, extraImports ...string) error {
	src, err := os.ReadFile(registryFileName)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		src = []byte(registryTemplate(modulePath))
	}

	start, end := blockMarkers(name)
	block := start + "\n" + strings.TrimRight(body, "\n") + "\n" + end

	imports := append([]string{fmt.Sprintf("%q", modulePath+"/handlers")}, extraImports...)
	content := ensureImports(string(src), imports)
	blockRe := regexp.MustCompile(regexp.QuoteMeta(start) + `(?s).*?` + regexp.QuoteMeta(end))

	if blockRe.MatchString(content) {
		content = blockRe.ReplaceAllString(content, block)
	} else {
		braceIdx := strings.LastIndex(content, "}")
		if braceIdx == -1 {
			return fmt.Errorf("%s is malformed: no closing brace for RegisterGeneratedRoutes", registryFileName)
		}
		insertion := "\t" + strings.ReplaceAll(block, "\n", "\n\t") + "\n"
		content = content[:braceIdx] + insertion + content[braceIdx:]
	}

	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("formatting %s: %w", registryFileName, err)
	}

	return os.WriteFile(registryFileName, formatted, 0o644)
}
